DROP DATABASE IF EXISTS heroes;
CREATE DATABASE IF NOT EXISTS heroes;
USE heroes;

CREATE TABLE images (
    id SERIAL PRIMARY KEY,
    listing VARCHAR NOT NULL,
    url1 VARCHAR NOT NULL,
    url2 VARCHAR NOT NULL,
    url3 VARCHAR NOT NULL,
    url4 VARCHAR NOT NULL,
    url5 VARCHAR NOT NULL
);


